// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"github.com/GUET-BAT/Astraios-S/user-service/internal/logic"
	"github.com/GUET-BAT/Astraios-S/user-service/internal/svc"
	"github.com/GUET-BAT/Astraios-S/user-service/pb/userpb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) VerifyPassword(ctx context.Context, in *userpb.VerifyPasswordRequest) (*userpb.VerifyPasswordResponse, error) {
	l := logic.NewVerifyPasswordLogic(ctx, s.svcCtx)
	return l.VerifyPassword(in)
}

func (s *UserServiceServer) Register(ctx context.Context, in *userpb.RegisterRequest) (*userpb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) GetUserData(ctx context.Context, in *userpb.UserDataRequest) (*userpb.UserDataResponse, error) {
	l := logic.NewGetUserDataLogic(ctx, s.svcCtx)
	return l.GetUserData(in)
}
