// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_service.proto

package server

import (
	"context"

	"user-service/internal/logic"
	"user-service/internal/svc"
	"user-service/pb/github.com/astraios/grpc/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) VerifyPassword(ctx context.Context, in *user.VerifyPasswordRequest) (*user.VerifyPasswordResponse, error) {
	l := logic.NewVerifyPasswordLogic(ctx, s.svcCtx)
	return l.VerifyPassword(in)
}

func (s *UserServiceServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) GetUserId(ctx context.Context, in *user.UserDataRequest) (*user.UserDataResponse, error) {
	l := logic.NewGetUserIdLogic(ctx, s.svcCtx)
	return l.GetUserId(in)
}
