// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user_service.proto

package userservice

import (
	"context"

	"user-service/pb/github.com/astraios/grpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RegisterRequest        = user.RegisterRequest
	RegisterResponse       = user.RegisterResponse
	UserDataRequest        = user.UserDataRequest
	UserDataResponse       = user.UserDataResponse
	VerifyPasswordRequest  = user.VerifyPasswordRequest
	VerifyPasswordResponse = user.VerifyPasswordResponse

	UserService interface {
		VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		GetUserId(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.VerifyPassword(ctx, in, opts...)
}

func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserService) GetUserId(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserId(ctx, in, opts...)
}
