// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: astraios_auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_astraios_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{0}
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_astraios_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_astraios_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_astraios_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_astraios_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{4}
}

// 刷新令牌请求
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_astraios_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 刷新令牌响应
type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_astraios_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// 单个 JWK
type Jwk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kty           string                 `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	Use           string                 `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Kid           string                 `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	Alg           string                 `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`
	N             string                 `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	E             string                 `protobuf:"bytes,6,opt,name=e,proto3" json:"e,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_astraios_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{7}
}

func (x *Jwk) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *Jwk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Jwk) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Jwk) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Jwk) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Jwk) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

// JWKS 响应
type JwksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Jwk                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JwksResponse) Reset() {
	*x = JwksResponse{}
	mi := &file_astraios_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwksResponse) ProtoMessage() {}

func (x *JwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_astraios_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwksResponse.ProtoReflect.Descriptor instead.
func (*JwksResponse) Descriptor() ([]byte, []int) {
	return file_astraios_auth_proto_rawDescGZIP(), []int{8}
}

func (x *JwksResponse) GetKeys() []*Jwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_astraios_auth_proto protoreflect.FileDescriptor

const file_astraios_auth_proto_rawDesc = "" +
	"\n" +
	"\x13astraios_auth.proto\x12\rastraios.auth\"\a\n" +
	"\x05Empty\"Z\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\"n\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshTokenJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04codeR\x03msg\"]\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\")\n" +
	"\x10RegisterResponseJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04codeR\x03msg\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"u\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshTokenJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\x04codeR\x03msg\"i\n" +
	"\x03Jwk\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x10\n" +
	"\x03alg\x18\x04 \x01(\tR\x03alg\x12\f\n" +
	"\x01n\x18\x05 \x01(\tR\x01n\x12\f\n" +
	"\x01e\x18\x06 \x01(\tR\x01e\"6\n" +
	"\fJwksResponse\x12&\n" +
	"\x04keys\x18\x01 \x03(\v2\x12.astraios.auth.JwkR\x04keys2\xb5\x02\n" +
	"\vAuthService\x12B\n" +
	"\x05Login\x12\x1b.astraios.auth.LoginRequest\x1a\x1c.astraios.auth.LoginResponse\x12K\n" +
	"\bRegister\x12\x1e.astraios.auth.RegisterRequest\x1a\x1f.astraios.auth.RegisterResponse\x12W\n" +
	"\fRefreshToken\x12\".astraios.auth.RefreshTokenRequest\x1a#.astraios.auth.RefreshTokenResponse\x12<\n" +
	"\aGetJwks\x12\x14.astraios.auth.Empty\x1a\x1b.astraios.auth.JwksResponseBT\n" +
	"\x16com.astraios.grpc.authP\x01Z8github.com/GUET-BAT/Astraios-S/gateway-service/pb/authpbb\x06proto3"

var (
	file_astraios_auth_proto_rawDescOnce sync.Once
	file_astraios_auth_proto_rawDescData []byte
)

func file_astraios_auth_proto_rawDescGZIP() []byte {
	file_astraios_auth_proto_rawDescOnce.Do(func() {
		file_astraios_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraios_auth_proto_rawDesc), len(file_astraios_auth_proto_rawDesc)))
	})
	return file_astraios_auth_proto_rawDescData
}

var file_astraios_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_astraios_auth_proto_goTypes = []any{
	(*Empty)(nil),                // 0: astraios.auth.Empty
	(*LoginRequest)(nil),         // 1: astraios.auth.LoginRequest
	(*LoginResponse)(nil),        // 2: astraios.auth.LoginResponse
	(*RegisterRequest)(nil),      // 3: astraios.auth.RegisterRequest
	(*RegisterResponse)(nil),     // 4: astraios.auth.RegisterResponse
	(*RefreshTokenRequest)(nil),  // 5: astraios.auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 6: astraios.auth.RefreshTokenResponse
	(*Jwk)(nil),                  // 7: astraios.auth.Jwk
	(*JwksResponse)(nil),         // 8: astraios.auth.JwksResponse
}
var file_astraios_auth_proto_depIdxs = []int32{
	7, // 0: astraios.auth.JwksResponse.keys:type_name -> astraios.auth.Jwk
	1, // 1: astraios.auth.AuthService.Login:input_type -> astraios.auth.LoginRequest
	3, // 2: astraios.auth.AuthService.Register:input_type -> astraios.auth.RegisterRequest
	5, // 3: astraios.auth.AuthService.RefreshToken:input_type -> astraios.auth.RefreshTokenRequest
	0, // 4: astraios.auth.AuthService.GetJwks:input_type -> astraios.auth.Empty
	2, // 5: astraios.auth.AuthService.Login:output_type -> astraios.auth.LoginResponse
	4, // 6: astraios.auth.AuthService.Register:output_type -> astraios.auth.RegisterResponse
	6, // 7: astraios.auth.AuthService.RefreshToken:output_type -> astraios.auth.RefreshTokenResponse
	8, // 8: astraios.auth.AuthService.GetJwks:output_type -> astraios.auth.JwksResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_astraios_auth_proto_init() }
func file_astraios_auth_proto_init() {
	if File_astraios_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraios_auth_proto_rawDesc), len(file_astraios_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraios_auth_proto_goTypes,
		DependencyIndexes: file_astraios_auth_proto_depIdxs,
		MessageInfos:      file_astraios_auth_proto_msgTypes,
	}.Build()
	File_astraios_auth_proto = out.File
	file_astraios_auth_proto_goTypes = nil
	file_astraios_auth_proto_depIdxs = nil
}
