// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package commonservice

import (
	"context"

	"github.com/GUET-BAT/Astraios-S/common-service/pb/commonpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoadConfigRequest  = commonpb.LoadConfigRequest
	LoadConfigResponse = commonpb.LoadConfigResponse

	CommonService interface {
		LoadConfig(ctx context.Context, in *LoadConfigRequest, opts ...grpc.CallOption) (*LoadConfigResponse, error)
	}

	defaultCommonService struct {
		cli zrpc.Client
	}
)

func NewCommonService(cli zrpc.Client) CommonService {
	return &defaultCommonService{
		cli: cli,
	}
}

func (m *defaultCommonService) LoadConfig(ctx context.Context, in *LoadConfigRequest, opts ...grpc.CallOption) (*LoadConfigResponse, error) {
	client := commonpb.NewCommonServiceClient(m.cli.Conn())
	return client.LoadConfig(ctx, in, opts...)
}
