// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Type     int32  `json:"type,optional"`
}

type RegisterResponse struct {
	Code int32 `json:"code"`
}

type UserDataRequest struct {
	Userid string `path:"userid"`
}

type UserDataResponse struct {
	UserId          string `json:"userId"`
	Nickname        string `json:"nickname"`
	Avatar          string `json:"avatar"`
	Gender          int32  `json:"gender"`
	Birthday        string `json:"birthday"`
	Bio             string `json:"bio"`
	BackgroundImage string `json:"backgroundImage"`
	Country         string `json:"country"`
	Province        string `json:"province"`
	City            string `json:"city"`
	School          string `json:"school"`
	Major           string `json:"major"`
	GraduationYear  int32  `json:"graduationYear"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}
