// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AvatarUrlRequest struct {
}

type AvatarUrlResponse struct {
	AvatarUrl string `json:"avatar_url"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Type     int32  `json:"type,optional"`
}

type LoginResponse struct {
	Code int32             `json:"code"`
	Msg  string            `json:"message,optional"`
	Data LoginResponseData `json:"data"`
}

type LoginResponseData struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"message,optional"`
	Data string `json:"data,optional"`
}

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Type     int32  `json:"type,optional"`
}

type RegisterResponse struct {
	Code int32  `json:"code"`
	Msg  string `json:"message,optional"`
	Data string `json:"data,optional"`
}

type UserDataRequest struct {
	UserInfo UserInfo `json:"user_info,optional"`
}

type UserDataResponse struct {
	Code int32                `json:"code"`
	Msg  string               `json:"message"`
	Data UserDataResponseData `json:"data,optional"`
}

type UserDataResponseData struct {
	UserInfo UserInfo `json:"user_info"`
}

type UserInfo struct {
	Userid          string `json:"user_id,optional"`
	Nickname        string `json:"nickname"`
	Avatar          string `json:"avatar"`
	Gender          int32  `json:"gender"`
	Birthday        string `json:"birthday"`
	Bio             string `json:"bio"`
	BackgroundImage string `json:"backgroundImage"`
	Country         string `json:"country"`
	Province        string `json:"province"`
	City            string `json:"city"`
	School          string `json:"school"`
	Major           string `json:"major"`
	GraduationYear  int32  `json:"graduation_year"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}
