// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "github.com/GUET-BAT/Astraios-S/gateway-service/internal/handler/user"
	"github.com/GUET-BAT/Astraios-S/gateway-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/users/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/users/logout",
					Handler: user.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/users/presign-url",
					Handler: user.GetAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/users/presign-url",
					Handler: user.SetAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/users/user-data",
					Handler: user.GetUserDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/users/user-data",
					Handler: user.SetUserDataHandler(serverCtx),
				},
			}...,
		),
	)
}
