// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package server

import (
	"context"

	"github.com/GUET-BAT/Astraios-S/common-service/internal/logic"
	"github.com/GUET-BAT/Astraios-S/common-service/internal/svc"
	"github.com/GUET-BAT/Astraios-S/common-service/pb/commonpb"
)

type CommonServiceServer struct {
	svcCtx *svc.ServiceContext
	commonpb.UnimplementedCommonServiceServer
}

func NewCommonServiceServer(svcCtx *svc.ServiceContext) *CommonServiceServer {
	return &CommonServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServiceServer) LoadConfig(ctx context.Context, in *commonpb.LoadConfigRequest) (*commonpb.LoadConfigResponse, error) {
	l := logic.NewLoadConfigLogic(ctx, s.svcCtx)
	return l.LoadConfig(in)
}
