// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: common.proto

package server

import (
	"context"

	"common-service/internal/logic"
	"common-service/internal/svc"
	"common-service/pb/github.com/astraios/grpc/common"
)

type CommonServiceServer struct {
	svcCtx *svc.ServiceContext
	common.UnimplementedCommonServiceServer
}

func NewCommonServiceServer(svcCtx *svc.ServiceContext) *CommonServiceServer {
	return &CommonServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServiceServer) LoadConfig(ctx context.Context, in *common.LoadConfigRequest) (*common.LoadConfigResponse, error) {
	l := logic.NewLoadConfigLogic(ctx, s.svcCtx)
	return l.LoadConfig(in)
}
